<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $template->name }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 20px; }
        .header p { margin: 5px 0 0; color: #666; }
        .filters { margin-bottom: 20px; font-size: 11px; color: #555; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 5px; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ auth()->user()->company->name ?? 'Creative ERP' }}</h1>
        <h2>{{ $template->name }}</h2>
        <p>Generated on {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    @if(!empty($filters))
    <div class="filters">
        <strong>Filters Applied:</strong>
        @foreach($filters as $key => $value)
            @if(is_array($value))
                {{ ucwords(str_replace('_', ' ', $key)) }}: {{ implode(', ', $value) }} | 
            @else
                {{ ucwords(str_replace('_', ' ', $key)) }}: {{ $value }} | 
            @endif
        @endforeach
    </div>
    @endif

    @include('admin.reports.exports.financial-table', ['data' => $data, 'type' => $template->type, 'filters' => $filters])

    <div class="footer">
        Generated by Creative ERP &bull; Page <span class="page-number"></span>
    </div>

</body>
</html>
