<?php

return [
    'Dashboard' => [
        ['route' => 'admin.dashboard', 'label' => 'Dashboard', 'active' => 'admin.dashboard'],
    ],
    'Productivity' => [
        ['route' => 'admin.calendar.index', 'label' => 'Calendar', 'permission' => 'calendar.view', 'active' => 'admin.calendar.*'],
        ['route' => 'admin.meetings.index', 'label' => 'Meetings', 'model' => \App\Models\Meeting::class, 'active' => 'admin.meetings.*'],
        ['route' => 'admin.time-tracking.index', 'label' => 'Time Tracking', 'model' => \App\Models\TimeEntry::class, 'active' => 'admin.time-tracking.index'],
        ['route' => 'admin.time-tracking.timesheet', 'label' => 'My Timesheet', 'permission' => 'time.view', 'active' => 'admin.time-tracking.timesheet'],
        ['route' => 'admin.approvals.index', 'label' => 'My Approvals', 'model' => \App\Models\Approval::class, 'active' => 'admin.approvals.*'],
        ['route' => 'admin.announcements.index', 'label' => 'Announcements', 'model' => \App\Models\Announcement::class, 'active' => 'admin.announcements.*'],
    ],
    'CRM & Sales' => [
        ['route' => 'admin.crm.leads.index', 'label' => 'Leads', 'model' => \App\Models\Lead::class, 'active' => 'admin.crm.leads.*'],
        ['route' => 'admin.crm.opportunities.index', 'label' => 'Opportunities', 'model' => \App\Models\Opportunity::class, 'active' => 'admin.crm.opportunities.*'],
        ['route' => 'admin.crm.pipelines.index', 'label' => 'Pipelines', 'model' => \App\Models\Pipeline::class, 'active' => 'admin.crm.pipelines.*'],
        ['route' => 'admin.crm.accounts.index', 'label' => 'Accounts', 'model' => \App\Models\Account::class, 'active' => 'admin.crm.accounts.*'],
        ['route' => 'admin.crm.contacts.index', 'label' => 'Contacts', 'model' => \App\Models\Contact::class, 'active' => 'admin.crm.contacts.*'],
        ['route' => 'admin.crm.quotations.index', 'label' => 'Quotations', 'model' => \App\Models\Quotation::class, 'active' => 'admin.crm.quotations.*'],
        ['route' => 'admin.clients.index', 'label' => 'Clients', 'model' => \App\Models\Client::class, 'active' => 'admin.clients.*'],
    ],
    'Projects' => [
        ['route' => 'admin.projects.index', 'label' => 'Projects', 'model' => \App\Models\Project::class, 'active' => ['admin.projects.index', 'admin.projects.create', 'admin.projects.edit', 'admin.projects.show', 'admin.projects.timeline']],
        ['route' => 'admin.projects.team.index', 'label' => 'Project Teams', 'model' => \App\Models\ProjectMember::class, 'active' => 'admin.projects.team.*'],
        ['route' => 'admin.projects.tasks.index', 'label' => 'Tasks', 'model' => \App\Models\Task::class, 'active' => 'admin.projects.tasks.*'],
        ['route' => 'admin.milestones.index', 'label' => 'Milestones', 'model' => \App\Models\Milestone::class, 'active' => 'admin.milestones.*'],
        ['route' => 'admin.material-requests.index', 'label' => 'Material Requests', 'permission' => 'material_request.view', 'active' => 'admin.material-requests.*'],
    ],
    'Procurement' => [
        ['route' => 'admin.procurement.suppliers.index', 'label' => 'Suppliers', 'model' => \App\Models\Supplier::class, 'active' => 'admin.procurement.suppliers.*'],
        ['route' => 'admin.procurement.requisitions.index', 'label' => 'Requisitions', 'model' => \App\Models\PurchaseRequisition::class, 'active' => 'admin.procurement.requisitions.*'],
        ['route' => 'admin.procurement.rfqs.index', 'label' => 'RFQs', 'model' => \App\Models\SupplierQuotation::class, 'active' => 'admin.procurement.rfqs.*'],
        ['route' => 'admin.procurement.pos.index', 'label' => 'Purchase Orders', 'model' => \App\Models\PurchaseOrder::class, 'active' => 'admin.procurement.pos.*'],
        ['route' => 'admin.procurement.receipts.index', 'label' => 'Goods Receipts', 'model' => \App\Models\GoodsReceipt::class, 'active' => 'admin.procurement.receipts.*'],
        ['route' => 'admin.procurement.invoices.index', 'label' => 'Purchase Invoices', 'model' => \App\Models\PurchaseInvoice::class, 'active' => 'admin.procurement.invoices.*'],
        ['route' => 'admin.procurement.payments.index', 'label' => 'Supplier Payments', 'model' => \App\Models\SupplierPayment::class, 'active' => 'admin.procurement.payments.*'],
    ],
    'Inventory' => [
        ['route' => 'admin.inventory.dashboard', 'label' => 'Inventory Dashboard', 'model' => \App\Models\Product::class, 'active' => 'admin.inventory.dashboard'],
        ['route' => 'admin.inventory.products.index', 'label' => 'Products', 'model' => \App\Models\Product::class, 'active' => 'admin.inventory.products.*'],
        ['route' => 'admin.inventory.categories.index', 'label' => 'Categories', 'model' => \App\Models\ProductCategory::class, 'active' => 'admin.inventory.categories.*'],
        ['route' => 'admin.inventory.brands.index', 'label' => 'Brands', 'model' => \App\Models\Brand::class, 'active' => 'admin.inventory.brands.*'],
        ['route' => 'admin.inventory.units.index', 'label' => 'Units of Measure', 'model' => \App\Models\UnitOfMeasure::class, 'active' => 'admin.inventory.units.*'],
        ['route' => 'admin.inventory.warehouses.index', 'label' => 'Warehouses', 'model' => \App\Models\Warehouse::class, 'active' => 'admin.inventory.warehouses.*'],
        ['route' => 'admin.inventory.adjustments.index', 'label' => 'Stock Adjustments', 'model' => \App\Models\InventoryAdjustment::class, 'active' => 'admin.inventory.adjustments.*'],
        ['route' => 'admin.inventory.transfers.index', 'label' => 'Stock Transfers', 'model' => \App\Models\InventoryTransfer::class, 'active' => 'admin.inventory.transfers.*'],
        ['route' => 'admin.inventory.reservations.index', 'label' => 'Reservations', 'model' => \App\Models\InventoryReservation::class, 'active' => 'admin.inventory.reservations.*'],
        ['route' => 'admin.inventory.stock-counts.index', 'label' => 'Stock Counts', 'model' => \App\Models\StockCount::class, 'active' => 'admin.inventory.stock-counts.*'],
        ['route' => 'admin.inventory.valuation.index', 'label' => 'Inventory Valuation', 'model' => \App\Models\InventoryValuation::class, 'active' => 'admin.inventory.valuation.*'],
    ],
    'Warehouse Operations' => [
        ['route' => 'admin.warehouse.tasks.index', 'label' => 'Warehouse Tasks', 'model' => \App\Models\WarehouseTask::class, 'active' => 'admin.warehouse.tasks.*'],
        ['route' => 'admin.warehouse.put-away.index', 'label' => 'Put Away', 'model' => \App\Models\WarehouseTask::class, 'active' => 'admin.warehouse.put-away.*'],
        ['route' => 'admin.warehouse.picking.index', 'label' => 'Picking', 'model' => \App\Models\WarehousePicking::class, 'active' => 'admin.warehouse.picking.*'],
        ['route' => 'admin.warehouse.packing.index', 'label' => 'Packing', 'model' => \App\Models\WarehousePacking::class, 'active' => 'admin.warehouse.packing.*'],
        ['route' => 'admin.warehouse.shipments.index', 'label' => 'Shipments', 'model' => \App\Models\WarehouseShipment::class, 'active' => 'admin.warehouse.shipments.*'],
        ['route' => 'admin.warehouse.returns.index', 'label' => 'Returns', 'model' => \App\Models\WarehouseReturn::class, 'active' => 'admin.warehouse.returns.*'],
        ['route' => 'admin.warehouse.cycle-counts.index', 'label' => 'Cycle Counts', 'model' => \App\Models\WarehouseCycleCount::class, 'active' => 'admin.warehouse.cycle-counts.*'],
        ['route' => 'admin.warehouse.movements.index', 'label' => 'Stock Movements', 'model' => \App\Models\WarehouseMovement::class, 'active' => 'admin.warehouse.movements.*'],
    ],
    'Finance & Accounting' => [
        ['route' => 'admin.finance.accounting.chart-of-accounts.index', 'label' => 'Chart of Accounts', 'model' => \App\Models\ChartOfAccount::class, 'active' => 'admin.finance.accounting.chart-of-accounts.*'],
        ['route' => 'admin.finance.accounting.journals.index', 'label' => 'Journal Entries', 'model' => \App\Models\Journal::class, 'active' => 'admin.finance.accounting.journals.*'],
        ['route' => 'admin.finance.accounting.ledger.index', 'label' => 'General Ledger', 'model' => \App\Models\GeneralLedger::class, 'active' => 'admin.finance.accounting.ledger.*'],
        ['route' => 'admin.finance.accounting.fiscal-periods.index', 'label' => 'Fiscal Settings', 'model' => \App\Models\FiscalYear::class, 'active' => 'admin.finance.accounting.fiscal-periods.*'],
        ['route' => 'admin.finance.budgets.index', 'label' => 'Budgets', 'model' => \App\Models\Budget::class, 'active' => 'admin.finance.budgets.*'],
        ['route' => 'admin.finance.invoices.index', 'label' => 'Invoices', 'model' => \App\Models\Invoice::class, 'active' => 'admin.finance.invoices.*'],
        ['route' => 'admin.finance.payments.index', 'label' => 'Payments', 'model' => \App\Models\Payment::class, 'active' => 'admin.finance.payments.*'],
        ['route' => 'admin.finance.credit-notes.index', 'label' => 'Credit Notes', 'model' => \App\Models\CreditNote::class, 'active' => 'admin.finance.credit-notes.*'],
        ['route' => 'admin.finance.refunds.index', 'label' => 'Refunds', 'model' => \App\Models\Refund::class, 'active' => 'admin.finance.refunds.*'],
        ['route' => 'admin.finance.settings', 'label' => 'Finance Settings', 'permission' => 'create', 'model' => \App\Models\Payment::class, 'active' => 'admin.finance.settings'],
    ],
    'Reports' => [
        ['route' => 'admin.reports.index', 'label' => 'Dashboard Reports', 'permission' => 'report.view', 'active' => 'admin.reports.*'],
        ['route' => 'admin.time-tracking.reports', 'label' => 'Productivity Reports', 'permission' => 'time.view', 'active' => 'admin.time-tracking.reports'],
        ['route' => 'admin.inventory.reports.index', 'label' => 'Inventory Reports', 'model' => \App\Models\Product::class, 'active' => 'admin.inventory.reports.*'],
    ],
    'Organization' => [
        ['route' => 'admin.companies.index', 'label' => 'Companies', 'model' => \App\Models\Company::class, 'active' => 'admin.companies.*'],
        ['route' => 'admin.branches.index', 'label' => 'Branches', 'model' => \App\Models\Branch::class, 'active' => 'admin.branches.*'],
        ['route' => 'admin.departments.index', 'label' => 'Departments', 'model' => \App\Models\Department::class, 'active' => 'admin.departments.*'],
    ],
    'Administration' => [
        ['route' => 'admin.users.index', 'label' => 'Users', 'model' => \App\Models\User::class, 'active' => 'admin.users.*'],
        ['route' => 'admin.roles.index', 'label' => 'Roles', 'permission' => 'role.view', 'active' => 'admin.roles.*'],
        ['route' => 'admin.permissions.index', 'label' => 'Permissions', 'permission' => 'permission.view', 'active' => 'admin.permissions.*'],
        ['route' => 'admin.workflows.index', 'label' => 'Workflow Builder', 'model' => \App\Models\ApprovalWorkflow::class, 'active' => 'admin.workflows.*'],
    ],
    'Website CMS' => [
        ['route' => 'admin.website-settings.index', 'label' => 'General Settings', 'permission' => 'superadmin', 'active' => 'admin.website-settings.*'],
        ['route' => 'admin.expertise-cards.index', 'label' => 'Expertise Cards', 'permission' => 'superadmin', 'active' => 'admin.expertise-cards.*'],
        ['route' => 'admin.website-projects.index', 'label' => 'Website Projects', 'permission' => 'superadmin', 'active' => 'admin.website-projects.*'],
    ],
    'Documents' => [
        ['route' => 'admin.document-categories.index', 'label' => 'Document Categories', 'model' => \App\Models\DocumentCategory::class, 'active' => 'admin.document-categories.*'],
        ['route' => 'admin.documents.index', 'label' => 'Documents', 'model' => \App\Models\Document::class, 'active' => 'admin.documents.*'],
    ],
];
